[package]
name = "wdk-mutex"
version = "1.1.0"
edition = "2021"
authors = ["Flux Sec <fluxsec@proton.me>"]
license = "MIT"
repository = "https://github.com/0xflux/wdk_mutex"
documentation = "https://0xflux.github.io/wdk-mutex"
readme = "Readme.md"
keywords = ["windows", "driver", "mutex", "kernel", "wdk"]
description = "An idiomatic Rust mutex type for Windows kernel driver development."

[package.metadata.wdk.driver-model]
driver-type = "WDM"

[lib]
crate-type = ["lib"]

[features]
default = []
nightly = ["wdk/nightly", "wdk-sys/nightly"]

[dependencies]
wdk = ">=0.3.0"
wdk-sys = ">=0.3.0"
wdk-alloc = ">=0.3.0"

[profile.dev]
panic = "abort"
lto = true

[profile.release]
panic = "abort"
lto = true